import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext.jsx";
import { useChatWidget } from "../context/ChatWidgetContext.jsx";
import { getDailyReport, getMyConsultations } from "../api.js";
import { dayNumber, monthShort } from "../utils/format.js";
import { buildProfessorBlocks } from "../utils/professorBlocks.js";
import PageHeader from "../components/PageHeader.jsx";
import StudentReservationCard from "../components/StudentReservationCard.jsx";
import ProfessorReservationBlock from "../components/ProfessorReservationBlock.jsx";
import styles from "./Home.module.css";

// "Tomorrow's report" is generated by an evening cron and persisted per
// professor. The Home card shows the latest persisted summary so the
// professor sees who is coming and what for, without having to dig into
// /my-consultations. Render is gated on role + state from the fetch:
//   - loading:           skeleton
//   - present:           summary card
//   - missing (404):     soft empty-state explaining when one will appear
//   - error (other):     stays hidden — never block the page on this
function fmtReportDate(date) {
  if (!date) return "";
  const d = new Date(`${date}T00:00:00`);
  if (Number.isNaN(d.getTime())) return date;
  return d.toLocaleDateString(undefined, {
    weekday: "long",
    day: "numeric",
    month: "short",
  });
}

function fmtGeneratedAt(iso) {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  return d.toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

export default function Home() {
  const { idToken, user } = useAuth();
  const { openWidget, bookingTick } = useChatWidget();
  const role = user?.role || "student";
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [report, setReport] = useState(null);
  const [reportState, setReportState] = useState("loading");

  // Re-runs on bookingTick so the upcoming preview reflects bookings the
  // student just made / cancelled through the floating chatbot. The
  // initial mount also runs through this effect, so there's no separate
  // first-load path to keep in sync.
  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const data = await getMyConsultations(idToken);
        if (alive) setItems(data.consultations || []);
      } catch {
        if (alive) setItems([]);
      } finally {
        if (alive) setLoading(false);
      }
    })();
    return () => {
      alive = false;
    };
  }, [idToken, bookingTick]);

  const isProfessor = role === "professor";

  useEffect(() => {
    if (!idToken || !isProfessor) {
      setReport(null);
      setReportState("idle");
      return undefined;
    }
    let alive = true;
    setReportState("loading");
    (async () => {
      try {
        const data = await getDailyReport(idToken);
        if (!alive) return;
        if (data && data.report) {
          setReport(data.report);
          setReportState("ready");
        } else {
          setReport(null);
          setReportState("empty");
        }
      } catch (e) {
        if (!alive) return;
        // The backend now returns 200 { report: null } when no row exists,
        // so this catch only runs for transient failures or older Lambda
        // deployments that still 404 with "No daily report has been
        // generated yet." We treat anything that looks like a missing-row
        // signal as the empty state, and hide the card on anything else
        // so a flaky backend doesn't break the dashboard.
        const msg = ((e && e.message) || "").toLowerCase();
        const looksLikeNoReport =
          msg.includes("daily report") ||
          msg.includes("no report") ||
          msg.includes("not yet generated") ||
          msg.includes("not been generated") ||
          msg.includes("404");
        if (looksLikeNoReport) {
          setReport(null);
          setReportState("empty");
        } else {
          setReport(null);
          setReportState("hidden");
        }
      }
    })();
    return () => {
      alive = false;
    };
  }, [idToken, isProfessor]);

  const sorted = useMemo(() => {
    const nowMs = Date.now();
    return [...items]
      .filter((c) => {
        if (!c.date) return false;
        const d = new Date(`${c.date}T${c.time || "00:00"}:00Z`);
        return Number.isFinite(d.getTime()) && d.getTime() > nowMs;
      })
      .sort((a, b) => {
        const da = `${a.date} ${a.time || ""}`;
        const db = `${b.date} ${b.time || ""}`;
        return da < db ? -1 : 1;
      });
  }, [items]);

  // Student preview: the next 3 booked sessions (cancelled rows are
  // visible on My Reservations as a record but the dashboard preview
  // is forward-looking, so we filter them out here).
  const studentUpcoming = useMemo(
    () => sorted.filter((c) => c.status === "booked").slice(0, 3),
    [sorted]
  );

  // Professor preview: take the first 1–2 BLOCKS so the visual
  // language matches My Reservations exactly (block headers + slot
  // rows). One block can already contain several slots, so two is
  // plenty for a dashboard.
  const professorPreviewBlocks = useMemo(() => {
    if (!isProfessor) return [];
    const blocks = buildProfessorBlocks(sorted);
    // Drop blocks where every row is fully cancelled — the home card
    // is "what's coming up", not "what fell through".
    const live = blocks.filter((b) =>
      b.rows.some((r) => r.group.some((c) => c.status === "booked"))
    );
    return live.slice(0, 2);
  }, [sorted, isProfessor]);

  const stats = useMemo(() => {
    if (isProfessor) {
      const blocks = buildProfessorBlocks(sorted);
      const slots = blocks.flatMap((b) => b.rows);
      const bookedSlots = slots.filter((r) =>
        r.group.some((c) => c.status === "booked")
      ).length;
      const next = sorted.find((c) => c.status === "booked");
      return { primary: bookedSlots, primaryLabel: "active sessions", next };
    }
    const active = sorted.filter((c) => c.status === "booked").length;
    const next = sorted.find((c) => c.status === "booked");
    return { primary: active, primaryLabel: "upcoming", next };
  }, [sorted, isProfessor]);

  const firstName = user?.displayName?.split(" ")[0] || "";

  const heroEyebrow = isProfessor ? "Professor dashboard" : "Student dashboard";
  const heroTitle = firstName ? `Welcome back, ${firstName}` : "Welcome back";
  const heroLead = isProfessor
    ? "Manage your published office hours and review the reservations students have made with you."
    : (
        <>
          Quick access to the faculty directory and your reserved sessions.
          The{" "}
          <button
            type="button"
            className={styles.assistantInline}
            onClick={() => openWidget()}
          >
            Academic Assistant
          </button>{" "}
          lives in the bottom-right corner — open it to ask anything in plain
          language.
        </>
      );

  const upcomingEyebrow = isProfessor
    ? "Upcoming reservations"
    : "Upcoming sessions";
  const upcomingTitle = isProfessor
    ? "Your next student reservations"
    : "Your next reserved sessions";

  const emptyTitle = isProfessor
    ? "No reservations yet."
    : "No upcoming sessions.";
  const emptyHint = isProfessor
    ? "Once students reserve one of your published office-hour blocks, you'll see them here."
    : "Browse the faculty directory or open the Academic Assistant to find a session that fits your week.";
  const emptyCta = isProfessor
    ? { to: "/calendar", label: "Open calendar" }
    : { to: "/professors", label: "Browse faculty" };

  return (
    <div className={styles.page}>
      <PageHeader
        size="hero"
        eyebrow={heroEyebrow}
        title={heroTitle}
        lead={heroLead}
      >
        <div className={styles.headerToolbar}>
          <div className={styles.stats}>
            <div className={styles.stat}>
              <span className={styles.statValue}>
                {loading ? "—" : stats.primary}
              </span>
              <span className={styles.statLabel}>{stats.primaryLabel}</span>
            </div>
            <div className={styles.statDivider} aria-hidden />
            <div className={styles.stat}>
              <span className={styles.statValue}>
                {loading
                  ? "—"
                  : stats.next
                    ? `${dayNumber(stats.next.date)} ${monthShort(stats.next.date)}`
                    : "—"}
              </span>
              <span className={styles.statLabel}>
                {stats.next?.time
                  ? `next · ${stats.next.time}`
                  : "next session"}
              </span>
            </div>
          </div>
        </div>
      </PageHeader>

      {isProfessor && reportState !== "hidden" && reportState !== "idle" && (
        <section className={styles.report} aria-label="Daily schedule report">
          <header className={styles.reportHead}>
            <span className={styles.reportRibbon} aria-hidden />
            <p className={styles.reportEyebrow}>Tomorrow at a glance</p>
            <h2 className={styles.reportTitle}>
              {reportState === "ready" && report?.date
                ? fmtReportDate(report.date)
                : "Your next-day schedule"}
            </h2>
          </header>

          {reportState === "loading" && (
            <div className={styles.reportSkeleton}>
              <div className={styles.skeletonRow} />
              <div className={styles.skeletonRow} />
              <div className={styles.skeletonRow} style={{ width: "70%" }} />
            </div>
          )}

          {reportState === "ready" && report && (
            <>
              <div className={styles.reportMeta}>
                <span>
                  <strong>{report.total}</strong>{" "}
                  consultation{report.total === 1 ? "" : "s"}
                </span>
                {report.generatedAt && (
                  <>
                    <span className={styles.reportDot} aria-hidden>
                      ·
                    </span>
                    <span className={styles.reportMetaMuted}>
                      Generated {fmtGeneratedAt(report.generatedAt)}
                    </span>
                  </>
                )}
              </div>
              <p className={styles.reportText}>{report.reportText}</p>
            </>
          )}

          {reportState === "empty" && (
            <p className={styles.reportEmpty}>
              No report yet — one is generated each evening for the next day's
              consultations. If you have bookings tomorrow, the summary will
              show up here automatically.
            </p>
          )}
        </section>
      )}

      <section className={styles.upcoming} aria-label="Upcoming">
        <header className={styles.upcomingHead}>
          <div className={styles.upcomingHeadCol}>
            <p className={styles.upcomingEyebrow}>{upcomingEyebrow}</p>
            <h2 className={styles.upcomingTitle}>{upcomingTitle}</h2>
          </div>
          <Link to="/my-consultations" className={styles.viewAll}>
            View all
            <span aria-hidden>→</span>
          </Link>
        </header>

        {loading && (
          <div className={styles.skeletonList}>
            {Array.from({ length: 3 }).map((_, i) => (
              <div key={i} className={styles.skeletonRow} />
            ))}
          </div>
        )}

        {!loading &&
          !isProfessor &&
          studentUpcoming.length === 0 && <UpcomingEmpty title={emptyTitle} hint={emptyHint} cta={emptyCta} />}

        {!loading &&
          isProfessor &&
          professorPreviewBlocks.length === 0 && <UpcomingEmpty title={emptyTitle} hint={emptyHint} cta={emptyCta} />}

        {!loading && !isProfessor && studentUpcoming.length > 0 && (
          <ul className={styles.list}>
            {studentUpcoming.map((c, i) => (
              <StudentReservationCard
                key={c.consultationId}
                c={c}
                index={i}
                compact
              />
            ))}
          </ul>
        )}

        {!loading && isProfessor && professorPreviewBlocks.length > 0 && (
          <ul className={styles.proBlockList}>
            {professorPreviewBlocks.map((block, i) => (
              <ProfessorReservationBlock
                key={`${block.date}T${block.startMin}`}
                block={block}
                index={i}
              />
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}

function UpcomingEmpty({ title, hint, cta }) {
  return (
    <div className={styles.empty}>
      <p className={styles.emptyTitle}>{title}</p>
      <p className={styles.emptyHint}>{hint}</p>
      <Link to={cta.to} className={styles.emptyCta}>
        {cta.label} <span aria-hidden>→</span>
      </Link>
    </div>
  );
}
